const mongoose = require("mongoose");
require("dotenv").config({ path: __dirname + "/../.env" });

const MONGO_URI =
  process.env.MONGO_URI ||
  "mongodb+srv://llmic:llmic123@cluster0.lfmymhm.mongodb.net/llmic?appName=Cluster0";

const categoryMap = {
  oncology: "6a4f9ea17ff5849ad0040cd0",
  generalPharma: "6a4f9ea17ff5849ad0040cd1",
  surgical: "6a4f9ea17ff5849ad0040cd2",
};

const demoProducts = [
  // ── ONCOLOGY (5 Products) ──
  {
    title: { en: "HERMIC 440" },
    name: "HERMIC 440",
    slug: "hermic-440",
    composition: "Trastuzumab 440 mg",
    dosageForm: "Lyophilized Powder for Injection",
    strength: "440 mg",
    manufacturer: "ILMIC Health Care Pvt. Ltd.",
    category: categoryMap.oncology,
    categories: [categoryMap.oncology],
    description: {
      en: "HERMIC 440 (Trastuzumab 440 mg) is a targeted humanized monoclonal antibody indicated for HER2-positive metastatic breast cancer and HER2-positive metastatic gastric cancer. Formulated for intravenous infusion under specialist oncology supervision.",
    },
    uses: "HER2-positive Metastatic Breast Cancer, Early Breast Cancer, Metastatic Gastric Cancer.",
    indications: "HER2-positive Metastatic Breast Cancer, Early Breast Cancer, Metastatic Gastric Cancer.",
    packaging: "1 Vial of 440 mg with 20 ml Bacteriostatic Water",
    storageConditions: "Store refrigerated at 2°C to 8°C. Do not freeze.",
    storage: "Store refrigerated at 2°C to 8°C. Do not freeze.",
    availability: "Sourcing Available",
    coldChain: true,
    status: "show",
    type: "trending",
    image: ["/products/hertuma.png"],
    tag: ["demo-product", "oncology", "monoclonal-antibody"],
    isDemo: true,
    stock: 50,
  },
  {
    title: { en: "ERLOMIC 150" },
    name: "ERLOMIC 150",
    slug: "erlomic-150",
    composition: "Erlotinib Hydrochloride 150 mg",
    dosageForm: "Tablet",
    strength: "150 mg",
    manufacturer: "ILMIC Health Care Pvt. Ltd.",
    category: categoryMap.oncology,
    categories: [categoryMap.oncology],
    description: {
      en: "ERLOMIC 150 (Erlotinib 150 mg) is an EGFR tyrosine kinase inhibitor indicated for the treatment of metastatic non-small cell lung cancer (NSCLC) with EGFR exon 19 deletions or exon 21 substitution mutations, and advanced pancreatic cancer.",
    },
    uses: "Metastatic Non-Small Cell Lung Cancer (NSCLC), Advanced Pancreatic Cancer.",
    indications: "Metastatic Non-Small Cell Lung Cancer (NSCLC), Advanced Pancreatic Cancer.",
    packaging: "30 Tablets per Bottle",
    storageConditions: "Store below 30°C in a dry place.",
    storage: "Store below 30°C in a dry place.",
    availability: "Sourcing Available",
    coldChain: false,
    status: "show",
    type: "popular",
    image: ["/products/tagrisso.png"],
    tag: ["demo-product", "oncology", "targeted-therapy"],
    isDemo: true,
    stock: 75,
  },
  {
    title: { en: "LENMIC 10" },
    name: "LENMIC 10",
    slug: "lenmic-10",
    composition: "Lenalidomide 10 mg",
    dosageForm: "Capsule",
    strength: "10 mg",
    manufacturer: "ILMIC Health Care Pvt. Ltd.",
    category: categoryMap.oncology,
    categories: [categoryMap.oncology],
    description: {
      en: "LENMIC 10 (Lenalidomide 10 mg) is an immunomodulatory agent with anti-angiogenic and antineoplastic properties. Indicated for multiple myeloma, myelodysplastic syndromes (MDS), and mantle cell lymphoma.",
    },
    uses: "Multiple Myeloma, Myelodysplastic Syndromes (MDS), Mantle Cell Lymphoma.",
    indications: "Multiple Myeloma, Myelodysplastic Syndromes (MDS), Mantle Cell Lymphoma.",
    packaging: "30 Capsules per Bottle",
    storageConditions: "Store below 25°C. Protect from moisture.",
    storage: "Store below 25°C. Protect from moisture.",
    availability: "Sourcing Available",
    coldChain: false,
    status: "show",
    type: "trending",
    image: ["/products/brukinsa.png"],
    tag: ["demo-product", "oncology", "immunomodulatory"],
    isDemo: true,
    stock: 60,
  },
  {
    title: { en: "BORMIC 3.5" },
    name: "BORMIC 3.5",
    slug: "bormic-3-5",
    composition: "Bortezomib 3.5 mg",
    dosageForm: "Lyophilized Powder for Injection",
    strength: "3.5 mg",
    manufacturer: "ILMIC Health Care Pvt. Ltd.",
    category: categoryMap.oncology,
    categories: [categoryMap.oncology],
    description: {
      en: "BORMIC 3.5 (Bortezomib 3.5 mg) is a reversible proteasome inhibitor designed to inhibit cancer cell survival pathways. Indicated for patients with relapsed or refractory multiple myeloma and mantle cell lymphoma.",
    },
    uses: "Relapsed / Refractory Multiple Myeloma, Mantle Cell Lymphoma.",
    indications: "Relapsed / Refractory Multiple Myeloma, Mantle Cell Lymphoma.",
    packaging: "Single-use Vial 3.5 mg",
    storageConditions: "Store below 25°C. Protect from light. Do not freeze.",
    storage: "Store below 25°C. Protect from light. Do not freeze.",
    availability: "Sourcing Available",
    coldChain: true,
    status: "show",
    type: "normal",
    image: ["/products/adcetris.png"],
    tag: ["demo-product", "oncology", "proteasome-inhibitor"],
    isDemo: true,
    stock: 40,
  },
  {
    title: { en: "CAPEMIC 500" },
    name: "CAPEMIC 500",
    slug: "capemic-500",
    composition: "Capecitabine 500 mg",
    dosageForm: "Film-Coated Tablet",
    strength: "500 mg",
    manufacturer: "ILMIC Health Care Pvt. Ltd.",
    category: categoryMap.oncology,
    categories: [categoryMap.oncology],
    description: {
      en: "CAPEMIC 500 (Capecitabine 500 mg) is an orally administered fluoropyrimidine carbamate prodrug converted to 5-fluorouracil in tumor tissues. Indicated for adjuvant colon cancer, advanced colorectal cancer, and metastatic breast cancer.",
    },
    uses: "Colorectal Cancer, Metastatic Breast Cancer, Gastric Cancer.",
    indications: "Colorectal Cancer, Metastatic Breast Cancer, Gastric Cancer.",
    packaging: "100 Tablets per Box (10x10 Strips)",
    storageConditions: "Store below 30°C in a dry place.",
    storage: "Store below 30°C in a dry place.",
    availability: "Sourcing Available",
    coldChain: false,
    status: "show",
    type: "popular",
    image: ["/products/xospata.png"],
    tag: ["demo-product", "oncology", "chemotherapy"],
    isDemo: true,
    stock: 80,
  },

  // ── GENERAL PHARMA (5 Products) ──
  {
    title: { en: "AMOXMIC 500" },
    name: "AMOXMIC 500",
    slug: "amoxmic-500",
    composition: "Amoxicillin Trihydrate 500 mg",
    dosageForm: "Capsule",
    strength: "500 mg",
    manufacturer: "ILMIC Health Care Pvt. Ltd.",
    category: categoryMap.generalPharma,
    categories: [categoryMap.generalPharma],
    description: {
      en: "AMOXMIC 500 is a broad-spectrum aminopenicillin antibiotic indicated for respiratory tract infections, ENT infections, urinary tract infections, and skin infections caused by susceptible Gram-positive and Gram-negative bacteria.",
    },
    uses: "Bronchitis, Pneumonia, Tonsillitis, Sinusitis, Otitis Media, Urinary Tract Infections.",
    indications: "Bronchitis, Pneumonia, Tonsillitis, Sinusitis, Otitis Media, Urinary Tract Infections.",
    packaging: "10 Strips of 10 Capsules per Box",
    storageConditions: "Store below 25°C in a cool, dry place.",
    storage: "Store below 25°C in a cool, dry place.",
    availability: "Sourcing Available",
    coldChain: false,
    status: "show",
    type: "trending",
    image: ["/products/capsule_bottle.png"],
    tag: ["demo-product", "general-pharma", "antibiotic"],
    isDemo: true,
    stock: 150,
  },
  {
    title: { en: "PANMIC 40" },
    name: "PANMIC 40",
    slug: "panmic-40",
    composition: "Pantoprazole Sodium Gastro-Resistant 40 mg",
    dosageForm: "Tablet",
    strength: "40 mg",
    manufacturer: "ILMIC Health Care Pvt. Ltd.",
    category: categoryMap.generalPharma,
    categories: [categoryMap.generalPharma],
    description: {
      en: "PANMIC 40 is a potent proton pump inhibitor (PPI) that suppresses gastric acid secretion by inhibiting H+/K+-ATPase. Indicated for GERD, reflux esophagitis, gastric ulcers, and Zollinger-Ellison syndrome.",
    },
    uses: "Gastroesophageal Reflux Disease (GERD), Gastric Ulcers, Duodenal Ulcers, Acid Reflux.",
    indications: "Gastroesophageal Reflux Disease (GERD), Gastric Ulcers, Duodenal Ulcers, Acid Reflux.",
    packaging: "10 Strips of 10 Tablets per Box",
    storageConditions: "Store below 30°C. Protect from moisture.",
    storage: "Store below 30°C. Protect from moisture.",
    availability: "Sourcing Available",
    coldChain: false,
    status: "show",
    type: "popular",
    image: ["/products/ramiven.png"],
    tag: ["demo-product", "general-pharma", "gastroenterology"],
    isDemo: true,
    stock: 200,
  },
  {
    title: { en: "MORMIC 500" },
    name: "MORMIC 500",
    slug: "mormic-500",
    composition: "Metformin Hydrochloride Extended Release 500 mg",
    dosageForm: "Extended-Release Tablet",
    strength: "500 mg",
    manufacturer: "ILMIC Health Care Pvt. Ltd.",
    category: categoryMap.generalPharma,
    categories: [categoryMap.generalPharma],
    description: {
      en: "MORMIC 500 ER is a biguanide antihyperglycemic agent formulated for extended release. Indicated for improving glycemic control in adults with type 2 diabetes mellitus alongside diet and exercise.",
    },
    uses: "Type 2 Diabetes Mellitus, Glycemic Control, Insulin Resistance Support.",
    indications: "Type 2 Diabetes Mellitus, Glycemic Control, Insulin Resistance Support.",
    packaging: "10 Strips of 15 Tablets per Box",
    storageConditions: "Store below 25°C. Keep away from direct sunlight.",
    storage: "Store below 25°C. Keep away from direct sunlight.",
    availability: "Sourcing Available",
    coldChain: false,
    status: "show",
    type: "normal",
    image: ["/products/kryxana.png"],
    tag: ["demo-product", "general-pharma", "antidiabetic"],
    isDemo: true,
    stock: 180,
  },
  {
    title: { en: "ATORMIC 20" },
    name: "ATORMIC 20",
    slug: "atormic-20",
    composition: "Atorvastatin Calcium 20 mg",
    dosageForm: "Film-Coated Tablet",
    strength: "20 mg",
    manufacturer: "ILMIC Health Care Pvt. Ltd.",
    category: categoryMap.generalPharma,
    categories: [categoryMap.generalPharma],
    description: {
      en: "ATORMIC 20 is a selective competitive inhibitor of HMG-CoA reductase. Indicated for reducing elevated total cholesterol, LDL-C, and triglycerides in primary hypercholesterolemia and cardiovascular prevention.",
    },
    uses: "Hypercholesterolemia, Dyslipidemia, Cardiovascular Disease Prevention.",
    indications: "Hypercholesterolemia, Dyslipidemia, Cardiovascular Disease Prevention.",
    packaging: "10 Strips of 10 Tablets per Box",
    storageConditions: "Store below 30°C in a dry place.",
    storage: "Store below 30°C in a dry place.",
    availability: "Sourcing Available",
    coldChain: false,
    status: "show",
    type: "popular",
    image: ["/products/lorbriqua.png"],
    tag: ["demo-product", "general-pharma", "cardiovascular"],
    isDemo: true,
    stock: 140,
  },
  {
    title: { en: "TELMIC 40" },
    name: "TELMIC 40",
    slug: "telmic-40",
    composition: "Telmisartan 40 mg",
    dosageForm: "Tablet",
    strength: "40 mg",
    manufacturer: "ILMIC Health Care Pvt. Ltd.",
    category: categoryMap.generalPharma,
    categories: [categoryMap.generalPharma],
    description: {
      en: "TELMIC 40 is a long-acting angiotensin II receptor blocker (ARB) indicated for the treatment of essential hypertension and reduction of cardiovascular morbidity in high-risk adult patients.",
    },
    uses: "Essential Hypertension, High Blood Pressure, Cardiovascular Protection.",
    indications: "Essential Hypertension, High Blood Pressure, Cardiovascular Protection.",
    packaging: "10 Strips of 14 Tablets per Box",
    storageConditions: "Store below 25°C. Protect from light and moisture.",
    storage: "Store below 25°C. Protect from light and moisture.",
    availability: "Sourcing Available",
    coldChain: false,
    status: "show",
    type: "normal",
    image: ["/products/lynparza.png"],
    tag: ["demo-product", "general-pharma", "antihypertensive"],
    isDemo: true,
    stock: 120,
  },

  // ── SURGICAL (5 Products) ──
  {
    title: { en: "SURGIMIC SUTURE 3-0" },
    name: "SURGIMIC SUTURE 3-0",
    slug: "surgimic-suture-3-0",
    composition: "Braided Synthetic Absorbable Polyglactin 910 Suture",
    dosageForm: "Surgical Suture",
    strength: "Size 3-0 (70 cm)",
    manufacturer: "ILMIC Health Care Pvt. Ltd.",
    category: categoryMap.surgical,
    categories: [categoryMap.surgical],
    description: {
      en: "SurgiMic Suture 3-0 is a sterile synthetic absorbable braided suture composed of polyglactin 910 coated with calcium stearate. Features excellent tensile strength, smooth tissue passage, and reliable knot security.",
    },
    uses: "General Soft Tissue Approximation, Ligation, Gynecological & Abdominal Surgery.",
    indications: "General Soft Tissue Approximation, Ligation, Gynecological & Abdominal Surgery.",
    packaging: "Box of 12 Sterile Foil Packs with Reverse Cutting Needles",
    storageConditions: "Store below 25°C away from direct moisture and heat.",
    storage: "Store below 25°C away from direct moisture and heat.",
    availability: "Sourcing Available",
    coldChain: false,
    status: "show",
    type: "trending",
    image: ["/products/critical.png"],
    tag: ["demo-product", "surgical", "sutures"],
    isDemo: true,
    stock: 100,
  },
  {
    title: { en: "SURGIMIC GLOVE 7.5" },
    name: "SURGIMIC GLOVE 7.5",
    slug: "surgimic-glove-7-5",
    composition: "Natural Rubber Latex (Sterile Powder-Free)",
    dosageForm: "Surgical Gloves",
    strength: "Size 7.5 (Anatomical Fit)",
    manufacturer: "ILMIC Health Care Pvt. Ltd.",
    category: categoryMap.surgical,
    categories: [categoryMap.surgical],
    description: {
      en: "SurgiMic Surgical Gloves (Size 7.5) are sterile, powder-free natural rubber latex gloves designed for high tactile sensitivity and tear resistance during operative procedures. Feature textured palm and beaded cuffs.",
    },
    uses: "Surgical Procedures, Operating Room Barrier Protection, Sterile Clinical Use.",
    indications: "Surgical Procedures, Operating Room Barrier Protection, Sterile Clinical Use.",
    packaging: "Box of 50 Pairs (Individual Sterile Paper Pouches)",
    storageConditions: "Store in a cool, dry place. Protect from ozone and heat.",
    storage: "Store in a cool, dry place. Protect from ozone and heat.",
    availability: "Sourcing Available",
    coldChain: false,
    status: "show",
    type: "popular",
    image: ["/products/specialty.png"],
    tag: ["demo-product", "surgical", "gloves"],
    isDemo: true,
    stock: 250,
  },
  {
    title: { en: "SURGIMIC MESH 15x15" },
    name: "SURGIMIC MESH 15x15",
    slug: "surgimic-mesh-15x15",
    composition: "Non-Absorbable Polypropylene Monofilament Mesh",
    dosageForm: "Surgical Mesh",
    strength: "15 cm x 15 cm",
    manufacturer: "ILMIC Health Care Pvt. Ltd.",
    category: categoryMap.surgical,
    categories: [categoryMap.surgical],
    description: {
      en: "SurgiMic Polypropylene Mesh (15cm x 15cm) is a sterile, non-absorbable monofilament surgical mesh designed for abdominal wall hernia repair. Features optimal elasticity, tissue integration, and burst strength.",
    },
    uses: "Inguinal Hernia Repair, Ventral Hernia Repair, Abdominal Wall Reconstruction.",
    indications: "Inguinal Hernia Repair, Ventral Hernia Repair, Abdominal Wall Reconstruction.",
    packaging: "1 Mesh per Double-Sterile Pouch | Box of 5 Pouches",
    storageConditions: "Store below 30°C in a clean, dry room.",
    storage: "Store below 30°C in a clean, dry room.",
    availability: "Sourcing Available",
    coldChain: false,
    status: "show",
    type: "normal",
    image: ["/products/nephrology.png"],
    tag: ["demo-product", "surgical", "hernia-mesh"],
    isDemo: true,
    stock: 45,
  },
  {
    title: { en: "SURGIMIC DRACH 14" },
    name: "SURGIMIC DRACH 14",
    slug: "surgimic-drach-14",
    composition: "Medical-Grade PVC/Silicone Closed Suction Drain Set",
    dosageForm: "Drainage Kit",
    strength: "14 Fr Catheter with 400ml Bellow Reservoir",
    manufacturer: "ILMIC Health Care Pvt. Ltd.",
    category: categoryMap.surgical,
    categories: [categoryMap.surgical],
    description: {
      en: "SurgiMic Closed Wound Suction Drainage kit (14Fr) features a radio-opaque perforated drain catheter and 400ml spring bellow reservoir for continuous low-pressure suction after orthopedic, thoracic, or abdominal surgery.",
    },
    uses: "Post-Operative Wound Drainage, Hematoma Prevention, Surgical Fluid Collection.",
    indications: "Post-Operative Wound Drainage, Hematoma Prevention, Surgical Fluid Collection.",
    packaging: "Individual Sterile Blister Packaging | Box of 10 Sets",
    storageConditions: "Store at ambient room temperature in dry conditions.",
    storage: "Store at ambient room temperature in dry conditions.",
    availability: "Sourcing Available",
    coldChain: false,
    status: "show",
    type: "normal",
    image: ["/products/imported.png"],
    tag: ["demo-product", "surgical", "wound-drainage"],
    isDemo: true,
    stock: 70,
  },
  {
    title: { en: "SURGIMIC STAPLER 35W" },
    name: "SURGIMIC STAPLER 35W",
    slug: "surgimic-stapler-35w",
    composition: "Medical-Grade Stainless Steel Staples (35 Wide Staples)",
    dosageForm: "Skin Stapler",
    strength: "35 Wide Staples (6.9mm x 3.6mm)",
    manufacturer: "ILMIC Health Care Pvt. Ltd.",
    category: categoryMap.surgical,
    categories: [categoryMap.surgical],
    description: {
      en: "SurgiMic 35W Disposable Skin Stapler is pre-loaded with 35 wide stainless steel staples. Ergonomically engineered for fast, reliable surgical skin closure with minimal tissue trauma and uniform staple formation.",
    },
    uses: "Surgical Skin Closure, Incision Closure, Emergency Wound Closure.",
    indications: "Surgical Skin Closure, Incision Closure, Emergency Wound Closure.",
    packaging: "1 Disposable Stapler per Sterile Pack | Box of 10 Packs",
    storageConditions: "Store below 30°C in dry, dust-free packaging.",
    storage: "Store below 30°C in dry, dust-free packaging.",
    availability: "Sourcing Available",
    coldChain: false,
    status: "show",
    type: "trending",
    image: ["/products/critical_care_injection.png"],
    tag: ["demo-product", "surgical", "skin-stapler"],
    isDemo: true,
    stock: 85,
  },
];

async function runSeed() {
  const isCleanup = process.argv.includes("--clean");

  try {
    console.log("Connecting to MongoDB...");
    await mongoose.connect(MONGO_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log("Connected to MongoDB!");

    const Product = mongoose.model(
      "Product",
      new mongoose.Schema({}, { strict: false })
    );

    if (isCleanup) {
      console.log("Cleaning up temporary demo products...");
      const result = await Product.deleteMany({
        $or: [{ isDemo: true }, { tag: { $in: ["demo-product"] } }],
      });
      console.log(`Deleted ${result.deletedCount} demo products.`);
    } else {
      console.log("Seeding temporary demo products...");

      // Clean existing demo products first to prevent duplicates
      await Product.deleteMany({
        $or: [{ isDemo: true }, { tag: { $in: ["demo-product"] } }],
      });

      const inserted = await Product.insertMany(demoProducts);
      console.log(`Successfully seeded ${inserted.length} demo products!`);
      console.log("Breakdown:");
      console.log("- Oncology: 5 products");
      console.log("- General Pharma: 5 products");
      console.log("- Surgical: 5 products");
    }

    process.exit(0);
  } catch (err) {
    console.error("Error during demo product seeding:", err.message);
    process.exit(1);
  }
}

runSeed();
